# Generated by Django 3.2.12 on 2026-02-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AntigravityAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gemini_flash_reset', models.DateTimeField(blank=True, null=True)),
                ('gemini_pro_reset', models.DateTimeField(blank=True, null=True)),
                ('opus_sonnet_reset', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
